### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Ajaythepower1606** [ZechBron/zVirus-Gen#1]
Brother you had done a great job ....
I am also learning but by reading your code I found that you had tried to make it as small as you can ....
Mostly you had or has been using shell code to make the tools I think you should make these in python3 so that the script will become small ..(I think)
Your work is fabulous. 😍😀👌✌

**Comment by ZechBron** [comment]
@Ajaythepower1606 Thanks bro. I will try updating this code.
I am a begineer. I will try writing in python.
Thanks
